import Footer from 'components/layout/Footer'
import Header from 'components/layout/Header'
import Layout from 'components/layout/Layout'
import styles from './index.module.scss'


export default function UserAgreement(props) {
  return (
    <Layout>
      <Header/>
      <div className={styles.root}>
        <div className={styles.content}>
          <h2>MONLYCOMPANY LIMITED User Agreement</h2>
          <p>Under the terms of this User Agreement, hereinafter referred to as the "Agreement", <b>MONLYCOMPANY LIMITED</b> (hereinafter referred to as the "Company") provides the Use of the site <a className={styles.contentsNonBlock} href='https://starmoonclub.com/'>https://starmoonclub.com/</a> (hereinafter referred to as the "Site") the right to use the Site's services and the Company's Services. All currently existing Services of the Site, as well as any development and/or addition of new ones, are subject to the Agreement.
The Agreement comes into force from the moment the User agrees to all the terms of the Agreement. The User is considered to have accepted the terms of the Agreement in full after completing the registration procedure or paying for any service of the site.
The current version of the Agreement is always available on the page at. The Agreement is subject to change without any special notice. The new version of the Agreement comes into force from the moment of its approval by the Company. If the Company has made changes to the Agreement that the User does not agree with, the User must stop using the Site's services.
This Agreement is a public offer of the Company and cannot be interpreted as establishing agency or partnership relations between the User and the Company.
It is not allowed to use the services of the Site and the Site for the purpose of making a profit.
The user is a legally capable citizen who has reached the age of 18.</p>
        <p>
        1. General terms of use of the Site
        </p>
        <p>1.1. Under the Agreement, the Company undertakes to provide the registered User with free and paid Services and Services, including services related to the provision of information and marketing materials, including in the form of SMS and E-mail newsletters, with the full list and order of receipt, which can always be found on the Website.
Actions performed in the User's Personal Account are considered as performed personally by the User and entail the creation of rights and obligations between the User and the Company under the terms of the Agreement. Information printed and certified by the Company from the User's Personal Account can be used by the Company as evidence of ordering Services in resolving disputes, including in court.</p>
        <p>1.2. The Company reserves the right to block or delete the User's account at any time and / or delete any User content without giving reasons, if it considers it inappropriate and violates the terms of the Agreement.</p>
        <p>1.3. Deletion of the User's account is also possible at any time, after the User agrees to cancel the account, by sending a written request to the Support Service.</p>
        <p>1.4. The Company has the right to dispose of statistical information related to the functioning of the Site, as well as User information to ensure targeted display of advertising information to various audiences of Site Users. For the purposes of organizing the operation and technical support of the Site, the Company has the technical ability to access Users ' personal pages, which it implements only in cases established by this User Agreement and current legislation.</p>
        <p>1.5. The Company has the right to send the User information about the development of the Site and its services, as well as to advertise its own activities and services.</p>
        <p>2. Obligations of the parties:</p>
        <p>2.1. User's Responsibilities:</p>
        <p>2.1.1. Comply with the provisions of the current UK legislation, the Agreement and other special documents (instructions, rules, etc.) Companies listed on the Site.</p>
        <p>2.1.2. Correctly perform the registration procedure as a User on the Site. When registering, the User must provide accurate and complete information about himself / herself on all issues proposed in the registration form, and keep this information up-to-date. In case of changes in contact details and other essential information, make timely changes to the registration form, and if it is not possible, notify the Company about this by e-mail</p>
        <p>2.1.3. Do not disclose or transfer to third parties their identification data, which can be used to authorize the User on the Site. The user is independently responsible for the security (resistance to detection) of the password chosen by him, and also independently ensures the confidentiality of his password.</p>
        <p>2.1.4. Do not use the results of providing Services and the answers (ideas) provided by the Company for the purpose of generating profit by replicating them and reproducing them repeatedly (publications in the press and other publications, public speeches, etc.) and in other ways.</p>
        <p>2.1.5.Prior to the conclusion of the Agreement (Agreement), get acquainted with its content, the content of the Site's Services, the list and cost of the Company's Services specified on the Company's Website and the Agreement.</p>
        <p>2.1.6. The User agrees that by expressing consent to receive the service, service package (service, package of services) It accepts all conditions of its provision to the Company (volume, cost, procedure and terms of receipt, provision). Expression of consent to receive a service, service package (service, service package) The User is considered to have made the last payment for the cost of a specific Service (service package) or/or service (service package) of the Company (including partial payment of the cost). </p>
        <p>2.1.7. It is explained and understood to the User that the Company's Services (package of services) and services (package of services) do not provide for the possibility of partial refusal of them for any reason. If the Client did not use the paid Service (s) On the Website within the time period set for its acceptance (including failure to arrive at the agreed time for a personal meeting with a specialist, etc.), as well as timely (no later than 24 hours before the service delivery date) did not warn about the need to postpone the service delivery time and/or refuse it, the Company has the right to consider these actions (omissions) as a unilateral refusal of the User from the Service and withhold 30% of the cost of the paid Service as a compensation.</p>
        <p>2.1.8. The User independently selects the service (s) and the method of receiving it, including the choice of the method and means of communication.</p>
        <p>2.1.9. The User understands and agrees that he / she must independently assess all risks associated with the use of the results of the provision of Services, including the assessment of its reliability, completeness or usefulness. The Company cannot guarantee 100% uninterrupted, fast, reliable and error-free operation of the Site's services, and that the results that can be obtained using the Site's services will be accurate, reliable and can be used to officially confirm any facts or as a basis for performing any actions.</p>
        <p>2.2. The Company undertakes to:</p>
        <p>2.2.1. Provide Services in accordance with the terms of the Agreement.</p>
        <p>2.2.2. Do not transfer the User's personal data to third parties without written consent, except in cases where this is necessary to fulfill the terms of the Agreement and provide Services or is provided for by the current legislation of the UK;</p>
        <p>3. Payment procedure</p>
        <p>3.1. Payment for the Company's Services is made on the basis of 100% prepayment.</p>
        <p>3.2. Payment methods are indicated in the corresponding section of the Site "Get points" and in other sections (Independent astrology, Individual consultations, Astrological trainings).</p>
        <p>3.3. For services related to transfer and acceptance of payments by telecom Operators, commissions may be set, the amount of which is subject to clarification from the Operator. The Commission amount is not included in the price of the Company's Services.  The User's consent to receive paid Services and the terms of their provision is considered received after the User confirms consent to pay for the Service in the corresponding section of the Site. The Company is not responsible for the actions of Mobile Operators and payment aggregators.</p>
        <p>3.4. The duration of the User's connection with the Consultant (including Internet chat) is rounded up to the full minute (per-minute billing).</p>
        <p>3.5. All expenses that the User will incur in connection with making a call, including those related to payment for long-distance and international communication services, are paid by the User independently, in accordance with the tariffs established by the telecom operators and are not subject to compensation by the Company.</p>
        <p>4. Contract validity period</p>
        <p>4.1. The Agreement comes into force from the moment of passing the User registration procedure on the Site) and is valid until the full fulfillment of the obligations assumed. In any case, the moment of passing the User registration procedure on the Site, the User performs one of the following actions:</p>
        <ul className={styles.list}>
          <li>fill in all the fields of the registration form (independently or with the help of the Company's support staff) on the Site and click on the "Calculate" or "Log in" field or confirm registration.</li>
          <li>payments, including partial payments, (by any method, in any place) service and/or services (package of services) of the Company;</li>
          <li>filling in all fields of the registration form (independently or with the help of the Company's support staff) on the Company's websites and clicking on the "Calculate" or "Log in" field or confirming registration, as well as receiving and paying for the Company's services provided by the latter on such sites;</li>
          <li>enter all the data required for receiving the Service (receiving the Service) in the form for creating an order and press the button to confirm receipt of the service.</li>
        </ul>
        <p>5. Exclusive rights</p>
        <p>5.1. All objects accessible through the Site's Services, including design elements, text, graphics, videos, and other objects (hereinafter referred to as materials), as well as any content posted on the Site, are subject to the exclusive rights of the Company, Users, and other copyright holders, respectively. The materials of the Site, as well as any content posted on the Site, may not be used without the prior permission of the copyright holder, except in cases expressly provided for in the Agreement.</p>
        <p>6. Use of the User's content and personal data.</p>
        <p>6.1. All personal information about the User is stored and processed by the Company in accordance with the terms of the Privacy Agreement</p>
        <p>7. Information support</p>
        <p>7.1. The User, by registering on the Site, as well as through the subscription form for informational and advertising materials located on the Site, expresses written consent to accept from the Company any reference and information materials containing information about news, discounts, promotions and other information related to the Site and Services, as well as news from Partners of the Site, including via email, SMS messages, postal items, and other methods.</p>
        <p>7.2 The User has the right to cancel the mailing list at any time by logging in to his Personal Account, unchecking the “Choose mailing list” item, or if the User wants to cancel any type of mailing, he must send a message via the feedback form on the Site.</p>
        <p>8. Confidentiality and protection of personal information</p>
        <p>8.1. The User — an individual, during registration, as well as during the provision of services under the Agreement, provides his / her personal data, including: Last name, first name, date of birth, mobile phone number, email address, and other information, is aware that they become available to third parties, and gives consent for their processing by the Company, both with the use of automation tools and without the use of automation tools, in particular, collection, storage and use for cooperation purposes under the Agreement, transfer to agents and third parties acting under contracts with the Company to fulfill the latter's obligations to the User.
The Company processes the personal data provided: — to register the User on the Site; - to fulfill its obligations to the User; - to evaluate and analyze work with the User; — to send information and marketing materials, including SMS newsletters;</p>
        <p>8.2. The Company undertakes not to disclose the information received from the User. Disclosure of information in accordance with reasonable and applicable legal requirements is not considered a violation of obligations.</p>
        <p>8.3. The User undertakes not to disclose information that is a Commercial Secret of the Company if such information has become available to the User. Commercial secrets under the Agreement are recognized as information of a production, technical, economic, organizational nature, including the results of intellectual activity, as well as information about the methods of carrying out professional activities that have actual or potential commercial value due to its unknown to third parties, to which third parties do not have free access on a legal basis.</p>
        <p>8.4. The User is solely responsible for providing accurate information and personal data, as well as for updating the provided data in case of any changes. In case of providing false information/unreliable data, the Company does not bear any responsibility for the fulfillment of obligations under the Agreement, as well as to third parties whose personal data were mistakenly (or for other reasons) indicated as personal (personal) data during User registration, or were used by the latter in the process and/or for providing services to the User. Services (fulfillment of obligations) under the Agreement. In the event of claims against the Company related to the processing of personal data of third parties, in connection with the provision of false information and personal data by the User, as well as in the event of losses incurred by the Company in this regard, the User compensates for these losses on the first request The company.</p>
        <p>8.5. The User's personal data is processed in accordance with the UK legislation and the regulation on the protection of personal data of clients in MONLYCOMPANY LIMITED, which can be found on the Company's website. The Company processes the User's personal data for the purpose of providing the User with services, including receiving personalized (targeted) advertising by the User; checking, researching and analyzing such data, which allows maintaining and improving the services and sections of the Site, as well as developing new services and sections of the Site. The Company takes all necessary measures to protect the User's personal data from unauthorized access, alteration, disclosure or destruction. The Company provides access to the User's personal data only to those employees, contractors and agents of the Company who need this information to ensure the functioning of the Site and provide Services to the User. The Company has the right to use the information provided by the User, including personal data, in order to ensure compliance with the requirements of the current UK legislation (including for the purpose of preventing and/or suppressing illegal and/or illegal actions of Users). Disclosure of information provided by the User can only be made in accordance with the current legislation of the United Kingdom at the request of the court, law enforcement agencies, as well as in other cases provided for by the legislation of the United Kingdom. Since the Company processes the User's personal data in order to fulfill the contract concluded between the Company and the User for the provision of Services, due to the provisions of the personal data legislation, the User's consent to the processing of his personal data is not required.</p>
        <p>8.6. The User is aware that the technology of operation of the Site services may require copying (reproduction) of the User's content by the Company, as well as its processing, and agrees to perform all necessary actions by the Company to bring the content in accordance with the technical requirements of a particular Site service. The User agrees that the Company has the right to use all data, materials (including photo/video materials) and information posted by the User on the Site (in the personal account, for the implementation of the Company's Services, etc.) without additional consent of the User to any extent and in any way that is not prohibited by the current legislation of the UK, as well as agrees to receive messages from the Company (including advertising messages).</p>
        <p>8.7. Unless proven otherwise by the User, any actions performed using the User's username and password are considered to have been performed by the corresponding User and third parties with their consent and knowledge. In case of unauthorized access to the User's username and password and/or personal page, or distribution of the username and password, the User must immediately inform the Company about this in accordance with the established procedure.</p>
        <p>8.8. The User is solely responsible for providing accurate information and personal data, as well as for updating the provided data in case of any changes. In case of providing false information/unreliable data, the Company does not bear any responsibility for the fulfillment of obligations under the Agreement, as well as to third parties whose personal data were mistakenly (or for other reasons) indicated as personal (personal) data during User registration, or were used by the latter in the process and/or for providing services to the User. Services (fulfillment of obligations) under the Agreement. In the event of claims against the Company related to the processing of personal data of third parties, in connection with the provision of false information by the User and their personal data, as well as in the event of losses incurred by the Company in this regard, the User compensates for these losses at the first request of the Company.</p>
        <p>9. Claims for deficiencies in the Services provided and/or the provision of Services</p>
        <p>9.1. Claims for the services provided under the Agreement must be submitted by registered Users in writing by sending a corresponding letter to the Customer Service, to the email address <a className={styles.contentsNonBlock} href='mailto:support@starmoon.com'>support@starmoon.com</a> within 3 (three) days from the date of occurrence of the grounds for filing the relevant claim. </p>
        <p>9.2. Claims of registered Users are subject to review by the Company within 10 (ten) business days from the date of their receipt.</p>
        <p>9.3. Refund of funds is made by the Company only upon the written application of the User, prepared in accordance with the form that can be found on the site in the relevant section and providing them with a document (s) confirming the fact and terms of payment for the service, as well as (if necessary, to determine the ownership of the User's indication data) additional documents at the request of the Company, within 10 (Ten) business days from the date of receipt of the specified documents and the Company's application. The application must contain the User's personal signature. Refunds are made in the amount, procedure and in accordance with the requirements of the current UK legislation.</p>
        <p>10. Final provisions.</p>
        <p>This Agreement is governed by and interpreted in accordance with the laws of the United Kingdom and is valid for all Users of the Site. All matters not covered by the Agreement are subject to resolution in accordance with the laws of the United Kingdom of Great BritainUnited Kingdom of Great Britain</p>
        <p>
        <div>Company Name:</div>
        <div>85 Great Portland Street, London, England, W1W 7LT</div>
        <div>MONLYCOMPANY LIMITED</div>
        <div>Company number 14236746</div>
        <a className={styles.contentsNonBlock} href='https://find-and-update.company-information.service.gov.uk/company/14236746'>https://find-and-update.company-information.service.gov.uk/company/14236746</a>
        </p>
        </div>
      </div>
      <Footer/>
    </Layout>
  )
}

